version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: taskdb
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "4000:4000"
    env_file: .env.example
    depends_on: [db]
volumes:
  db-data:
